### ISSUE TITLE
Error: Unable to find theme directory

### ISSUE THREAD

**Issue by theonesp** [MIT-LCP/critical-data#1]
When running `hugo serve`
I keep getting the error 

> Error: Unable to find theme Directory:~\Documents\GitHub\critical-data\themes\hugo-universal-theme

**Comment by tompollard** [comment]
We should perhaps include this theme as a subproject in GitHub, but for now you can install the  theme by navigating to the base directory for the project (i.e. `~\Documents\GitHub\critical-data\`, then:

1. creating a directory called `themes` (e.g. `mkdir themes`)
2. changing into the `themes` directory (e.g. `cd themes`)
3. cloning the theme that you need (e.g. `git clone git@github.com:devcows/hugo-universal-theme.git`)

For more information on themes, see: https://gohugo.io/themes/installing-and-using-themes/

**Comment by alistairewj** [comment]
You need to clone the repository recursively otherwise the theme, which is a submodule, isn't cloned. See the README, specifically command `git clone --recurse-submodules git@github.com:MIT-LCP/critical-data.git`

If you did that and it didn't work then the submodule might be configured incorrectly in which case just clone the hugo-universal-theme repo into the themes/hugo-universal-theme subfolder.

**Comment by alistairewj** [comment]
That would explain that!

**Comment by theonesp** [comment]
I had cloned the repo recursively when getting the error.
So I created a folder for the theme where the missing directory was and copied the files from [the hugo universal them](https://github.com/devcows/hugo-universal-theme), so pretty much what you recommended, it works now!
thanks

**Comment by tompollard** [comment]
@theonesp glad you manage to fix it! Rather than pushing changes directly to the master branch, please could you submit them via pull requests, so we can review before merging?
